name: Deploy 
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: aws sample app
        run: | 
             sudo rm -rf node_modules
             rm -f package-lock.json
             npm cache clean --force
             npm install
             #npm update
             quasar build
             aws s3 cp dist/spa/ s3://sensipletestapp1 --recursive --profile s3-deploy
             
             
