name: Deploy 
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: aws sample app
        run: | 
             sudo rm -rf node_modules
             rm -f package-lock.json
             npm cache clean --force
             cd /home/tinku/Desktop/sample
             export APP_API_URL="http://core-env.eba-baaiwawd.ap-south-1.elasticbeanstalk.com/"
             npm install
             npm update
             quasar build
             aws s3 cp dist/spa/ s3://webapp1102 --recursive
             aws cloudfront create-invalidation --distribution-id E39OIVD8TRHO0U --paths "/*"
             
             
